services:
  - type: web
    name: tp-final-backend   # ðŸ‘ˆ usa el mismo nombre que tu URL pÃºblica en Render
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start:prod"
    plan: free
    envVars:
      - key: DB_HOST
        value: gondola.proxy.rlwy.net
      - key: DB_PORT
        value: 52856
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: FhSmFuGTcOWDzqDToBdCMsgAyJWaEWeg
      - key: DB_NAME
        value: railway
      - key: JWT_SECRET
        value: secret
      - key: PORT
        value: 8080   # ðŸ‘ˆ Render pasa este valor a process.env.PORT, tu main.ts lo toma
