services:
  - type: web
    name: tf-final-backend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start:prod"
    plan: free
    envVars:
      - key: DB_HOST
        value: gondola.proxy.rlwy.net
      - key: DB_PORT
        value: 52856
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: FhSmFuGTcOWDzqDToBdCMsgAyJWaEWeg
      - key: DB_NAME
        value: railway
      - key: JWT_SECRET
        value: secret
      - key: PORT
        value: 8080
